#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here
    mainDiagonal=0
    secondDiagonal=0
    for i in range(0, len(arr)):
        for j in range(0, len(arr[i])):
            if(i==j):
                mainDiagonal+=arr[i][j]
            if((i + j) == (n - 1)):
                secondDiagonal+=arr[i][j]
    return abs(mainDiagonal-secondDiagonal)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
